[sentiment]
# huggingface or ollama # 둘중 하나를 선택.
usemodel = ollama

# usemodel = huggingface일 경우, 아래 설정 사용.
[huggingface]
huggingface_model =matthewburke/korean_sentiment
#beomi/KcELECTRA-base-v2022
# cardiffnlp/twitter-xlm-roberta-base-sentiment
# usemodel = ollama일 경우에 아래 설정 사용.
[ollama]
ollama_model = exaone3.5:7.8b
#llama3.1:8b
ollama_base_url = http://nabidream.duckdns.org:11139
ollama_timeout_sec = 30

[apiurl]
# The URL of the backend server to which the requests will be forwarded.
backend = http://nabidream.duckdns.org:8009


[eng_kor]
title = 영화명
directorNm = 감독
actorNm = 배우
repRlsDate = 개봉일
genreNm = 장르
